### ISSUE TITLE
[Request] Documentation of how to fully utilize this mod

### ISSUE THREAD

**Issue by MrKashew** [Jab125/TestModpackUpdateChecker#13]
I did ask on curseforge but reposting here for visibility - this mod could really benefit from a wiki or a video guide

How to properly populate hotfixes tab?
 - are these only for configs?
 - can it be used to add/remove/update mods in addition?

How to populate changelog?
The Action alone in instructions does not

What is BCC and how to utilize it, example?

**Comment by Jab125** [comment]
Check the discord support server linked in the CF and MR page.
